import { contactQQ, rewards, rewardText, rewardPolicy, formatAmount } from "./site";
import { navigationCopy } from "./navigation";
// Editable text for app/bounty/page.tsx. Keep layout and behavior in the component.
export const bountyCopy = {
  metadataTitle: navigationCopy.bountyLabel,
  metadataDescription: `欢迎为车身插画提供优化思路。小修改奖励 ${rewardText.small} 元，大修改奖励 ${rewardText.large} 元。${rewardPolicy}QQ：${contactQQ}，其他细节联系详聊。`,
  eyebrow: "02 / A LITTLE BETTER, TOGETHER",
  title: "下一笔",
  titleEmphasis: "想听听你的",
  lead: "喜欢它，也知道它还可以更好。",
  leadContinuation: "尤其是车头、尾部衔接与斜向观看的效果。如果你发现了不自然的地方，或有更好的表达，欢迎告诉我。",
  contactNote: `QQ ${contactQQ} · 其他细节联系详聊`,
  rewardAria: "悬赏金额",
  smallTitle: "小修改",
  smallEyebrow: "A BETTER DETAIL",
  currency: "¥",
  smallMin: formatAmount(rewards.small.min),
  rangeSeparator: "–",
  smallMax: formatAmount(rewards.small.max),
  smallDescription: "局部细节、配色或小范围衔接优化。",
  largeTitle: "大修改",
  largeEyebrow: "A BIGGER IDEA",
  largeAmount: rewardText.large,
  largeDescription: "较大范围的构图、画面关系或整体表达调整。",
  paymentPolicy: rewardPolicy,
  processTitle: "一个好想法，可以从这里开始。",
  stepOneNumber: "01",
  stepOneTitle: "指出具体位置",
  stepOneText: "在实拍上圈出你想修改的区域，说说哪里不够自然、为什么想改。",
  stepTwoNumber: "02",
  stepTwoTitle: "说清你的改法",
  stepTwoText: "文字、参考图或简单草图都可以，能清楚表达思路就很好。",
  stepThreeNumber: "03",
  stepThreeTitle: "确认采纳，立即支付",
  stepThreeText: `在 QQ 上沟通修改范围与对应金额；${rewardPolicy}具体配合方式联系详聊。`,
  faqTitle: "你可能想问",
  drawingQuestion: "一定要会画画，才能参与吗？",
  drawingAnswer: "不一定。欢迎清楚、具体的优化思路。参考图、照片标注或简单示意都可以帮助表达；如果涉及重新绘制，具体配合方式可再与车主沟通。",
  scopeQuestion: "小修改和大修改，怎么区分？",
  scopeAnswer: "页面中的说明用于展示大致方向。具体范围、是否涉及重绘或重新制作，以及最终奖励金额，需要在采纳前与车主确认。",
  rewardQuestion: "提出建议后，就会获得奖励吗？",
  rewardAnswer: `奖励以方案被采纳为条件。${rewardPolicy}不需要等施工完成。提出建议、开始讨论或进入候选，尚不等于已被采纳；修改范围与具体金额会提前沟通确认。`,
  channelQuestion: "我应该在哪里提交？",
  channelAnswer: `QQ：${contactQQ}。添加时备注“痛车优化”，可直接发送文字、参考图或草图。点击“我有一个想法”也可以复制投稿提纲；其他细节联系详聊。`,
  nextIntro: "先看看画面，再让想法慢慢长出来。",
  nextAction: "返回设计故事"
};
