import { navigationCopy } from "./navigation";
import { characters } from "./characters";
// Editable text for app/story/page.tsx. Keep layout and behavior in the component.
export const storyCopy = {
  metadataTitle: navigationCopy.storyLabel,
  metadataDescription: "祈夙与 ccdyz：关于现实自我、幻想未来，以及未来、希望与家的无断点插画痛车故事。",
  eyebrow: "01 / BETWEEN REALITY AND A DREAM",
  title: "一侧是真实的我",
  titleEmphasis: "一侧是未竟之梦",
  lead: "两个角色，一张被牵引的画布。",
  leadContinuation: "把未来、希望与家，画进同一段旅程。",
  directoryAria: "设计故事目录",
  charactersLink: "认识角色",
  meaningLink: "读懂细节",
  designLink: "设计初衷",
  charactersAria: `认识${characters.day.name}与 ${characters.night.name}`,
  meaningEyebrow: "EVERY DETAIL TELLS A STORY",
  meaningTitle: "每一处，都有来处。",
  meaningAside: "从一片星空，到一张画布",
  hoodAlt: "AI 车头示意：紫色自设在水面上牵引画布，将星空与祈夙的明亮世界相连；非实车照片",
  hoodTitle: "在水面上，奔向希望。",
  hoodCaption: "故事从引擎盖开始，沿着画布继续。",
  hoodDisclaimer: "AI 示意图 · 非实车照片",
  tension: "向希望奔跑，",
  tensionContinuation: "也为幻想留下破碎的伏笔",
  originLabel: "最初.",
  originQuestion: "我真的知道",
  originQuestionContinuation: "我想要什么吗？",
  originIntro: "一份关于这辆车，",
  originIntroContinuation: "也关于我自己的设计手记。",
  originOpening: "起初，只是因为家人总说：“你的车太难找了。”",
  originContext: "2025 年国庆的一次自驾游，让我看见了痛车作为个人表达的可能。此后近半年的推敲，把一个日常的小困扰，变成了关于自我的漫长追问。",
  originTitle: "抽离文字，引入故事",
  originSummary: "我想把整辆车当作一张连续的画面：主驾是真实的自设，副驾是寄托希望的祈夙；车头牵引幻想，车尾留下它可能破碎的伏笔。让角色、构图与衔接，都能回答一句“为什么”。",
  keywordFuture: "未来",
  keywordHope: "希望",
  keywordHome: "家",
  journalEyebrow: "THE DESIGN JOURNAL",
  journalAction: "读完整的设计手记",
  journalToggle: "展开 / 收起",
  journalSignature: "—— ccdyz，写在下一次出发之前",
  journalBack: "回到手记开头 ↑",
  nextIntro: "故事仍有遗憾，下一笔也许来自你。",
  nextAction: "看看修改悬赏"
};
